### PR TITLE
V1.0.0

### PR DESCRIPTION
**Pull request by natashapinto**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1)

### CODE REVIEW

**Review by aledj2 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1)* status: 0 of 5 files reviewed, 20 unresolved discussions (waiting on @aledj2 and @natashapinto)

___
*[dxapp.json, line 34 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ0Qdo7YMIek_vgxHw:-MqQ0Qdp1-4MRWnHbL4F:bs1nqmx) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/dxapp.json#L34)):*
> ```JSON
>       "help": "QC metrics specific for each panel",
>       "class": "file",
>       "patterns": ["*"],
> ```

also *Rdata?
___
*[README.md, line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-I956yWY4f9kJR5w:-MqQ-I956yWY4f9kJR5x:b-xprikz) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/README.md#L8)):*
> ```Markdown
> The app takes in a readcount file generated by https://github.com/moka-guys/dnanexus_ED_readcount_analysis, The docker image will pick the most appropriate reference samples and run exomedepth for a given sample. 
> 
> For further details on the usage of the docker image please refer to https://github.com/moka-guys/seglh-cnv/tree/main/exomedepth
> ```

can you link to the version of the docker image used here - can you state it's packaged and not downloaded from 001 - could it be?
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-Bmc97BRdA3zAe4t:-MqQ-Bmc97BRdA3zAe4u:b-37cfqf) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/README.md#L13)):*
> ```Markdown
> DNAnexus project name where the BAM and the indexes are stored
> Reference genome in build 37
> Readcount file generated using https://github.com/moka-guys/dnanexus_ED_readcount_analysis
> ```

formatting has been disrupted by underscores - may need to escape these
___
*[src/code.sh, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-RyU5l0wOv-A3Ko1:-MqQ-RyU5l0wOv-A3Ko2:brzmxxq) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L4)):*
> ```
> 
> #
> ```
not needed
___
*[src/code.sh, line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-Vmx9RgIqXSfRzb0:-MqQ-Vmx9RgIqXSfRzb1:b-anfsti) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L12)):*
> ```Shell
> 
> ### Set up parameters
> # split project name to get the NGS run number
> ```

(last element of name?) what if there are multiple libraries?
___
*[src/code.sh, line 19 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPyLM136lC7VVdL6uZ:-MqPyLM136lC7VVdL6u_:btlkyr3) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L19)):*
> ```Shell
> 
> #make output dir
> mkdir -p /home/dnanexus/out/exomedepth_output/exomedepth_output/$bedfile_prefix/
> ```

where is $bedfile_prefix made? this is a helper variable - should it be $subpanel_bed_prefix? 
___
*[src/code.sh, line 25 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-k8lElgom6Sjz06a:-MqQ-k8m2CMSetD3cqkQ:b-qvfuaj) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L25)):*
> ```Shell
> #
> # Download inputs
> # download all inputs
> ```

duplicate comment
___
*[src/code.sh, line 28 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-lu_1UsmXpEP1yiH:-MqQ-lu_1UsmXpEP1yiI:bpp6stj) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L28)):*
> ```Shell
> dx-download-all-inputs --parallel
> #
> #dx download "$bedfile"
> ```

not needed
___
*[src/code.sh, line 30 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-qQS34AdxhCPexv1:-MqQ-qQS34AdxhCPexv2:bp61xwd) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L30)):*
> ```Shell
> #dx download "$bedfile"
> 
> # make and cd to test dir
> ```

not making
___
*[src/code.sh, line 35 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPymyhCXQA3cYPc17D:-MqPymyhCXQA3cYPc17E:b-zi4ow0) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L35)):*
> ```Shell
> mark-section "determine run specific variables"
> #Extract samplename to name output files
> samplename=$(python -c "basename='$bedfile_prefix'; print basename.split('_R1')[0]")
> ```

as above where is $bedfile_prefix made? this is a helper variable - should it be $subpanel_bed_prefix?
___
*[src/code.sh, line 36 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ02mE0_eIUsD19cML:-MqQ02mE0_eIUsD19cMM:bfo7a1) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L36)):*
> ```Shell
> #Extract samplename to name output files
> samplename=$(python -c "basename='$bedfile_prefix'; print basename.split('_R1')[0]")
> echo $samplename
> ```

what is samplename showing? it's not for a specific sample?
___
*[src/code.sh, line 39 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ09VI91Vbth_RbY4w:-MqQ09VI91Vbth_RbY4x:b-vq8147) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L39)):*
> ```Shell
> echo "sub_panel_BED = " $subpanel_bed
> echo "reference_genome = " $reference_genome
> echo "panel = " $bamfile_pannumbers
> ```

All Pan numbers to be assessed using this BED file
___
*[src/code.sh, line 40 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ0GnP9cFHYr7IK3kL:-MqQ0GnP9cFHYr7IK3kM:bhd5k9s) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L40)):*
> ```Shell
> echo "reference_genome = " $reference_genome
> echo "panel = " $bamfile_pannumbers
> echo "bedfile_prefix = " $bedfile_prefix
> ```

where is this coming from?
___
*[src/code.sh, line 61 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzC_p63UIowX4y2QP:-MqPzC_p63UIowX4y2QQ:b-1oqhb6) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L61)):*
> ```Shell
> 
> 
> echo $ED_docker
> ```

? where is this coming from
___
*[src/code.sh, line 65 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzFeq8TC6wC-ZnrQp:-MqPzFeq8TC6wC-ZnrQq:b-2tyspe) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L65)):*
> ```Shell
> filecount="$(ls *001.ba* | grep . -c)"
> if (( $filecount < 6 )); then
> 	echo "LESS THAN THREE BAM FILES FOUND FOR THIS ANALYSIS" 1>&2
> ```

is this still valid/needed?
___
*[src/code.sh, line 72 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzLSPAnqrdJzgqOiy:-MqPzLSPAnqrdJzgqOiz:b-sdzvih) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L72)):*
> ```Shell
> cd ..
> 
> mark-section "setting up Exomedepth docker image"
> ```

not needed anymore?
___
*[src/code.sh, line 80 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzR8758saz8O7EdZ0:-MqPzR8758saz8O7EdZ1:b-xle8h4) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L80)):*
> ```Shell
> # Write log direct into output folder
> #Get read count for all samples
> docker load -i '/home/dnanexus/seglh_exomedepth.tgz'
> ```

assume this is packaged up in the app and in .gitignore? (gitignore not in the repo)
___
*[src/code.sh, line 82 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPz_q7491hD_phgfJn:-MqPz_q7491hD_phgfJo:b-m27nif) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L82)):*
> ```Shell
> docker load -i '/home/dnanexus/seglh_exomedepth.tgz'
> #Run command below to create panel of normals
> #docker run -v /home/dnanexus:/home/dnanexus seglh/exomedepth:5f792cb readCount.R /home/dnanexus/out/exomedepth_output/exomedepth_output/$bedfile_prefix/normals.RData $reference_genome_path $bedfile_path $bam_list
> ```

is this needed?
___
*[src/code.sh, line 85 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzgiXA17SSGH-1GW4:-MqPzgiXA17SSGH-1GW5:ble75da) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L85)):*
> ```Shell
> for bam in /home/dnanexus/to_test/*bam
> do
> samplename=$(python -c "basename='$bam'; print basename.split('/')[4].split('_R1')[0]")
> ```

what would this return. split on /? assume that's removing the filepath /home/dnanexus/to_test?
___
*[src/code.sh, line 89 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-040-h_DX_DkGu0g:-MqQ-040-h_DX_DkGu0h:brb50ag) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L89)):*
> ```
> v1.0.0
> ```
what is this? can you explain the cmd in comments please?

**Review by Graeme-Smith — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1)* status: 0 of 5 files reviewed, 21 unresolved discussions (waiting on @aledj2, @Graeme-Smith, and @natashapinto)

___
*[dxapp.json, line 34 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ0Qdo7YMIek_vgxHw:-MqoRcqTEpnyIflYWz1i:bb6un1j) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/dxapp.json#L34)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

also *Rdata?
</blockquote></details>

Done
___
*[README.md, line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-I956yWY4f9kJR5w:-MrP8wIu3EbxjrUfFaym:bchqc1m) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/README.md#L8)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you link to the version of the docker image used here - can you state it's packaged and not downloaded from 001 - could it be?
</blockquote></details>

The script now downloads this from the 001_ToolsReference project
___
*[README.md, line 13 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-Bmc97BRdA3zAe4t:-MqZUDTx2TSp3eI3D_xF:b-agtdze) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/README.md#L13)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

formatting has been disrupted by underscores - may need to escape these
</blockquote></details>

I've escaped the _ and checked in the mardkdown preview in VS Code and it is displaying OK for me 
___
*[src/code.sh, line 4 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-RyU5l0wOv-A3Ko1:-MqZW9RpA5Ltb9XZppm0:bja1yyh) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L4)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> 
> #
> ```
not needed
</blockquote></details>

Done.  Removed
___
*[src/code.sh, line 12 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-Vmx9RgIqXSfRzb0:-MrNX9aI2QKUOuqCuqgZ:b-npyrt9) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L12)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

(last element of name?) what if there are multiple libraries?
</blockquote></details>

Now uses sed regex to select single/multiple run numbers (although this variable is not currently used in the script): 



_Code snippet:_
```Shell
project_name=002_211119_A01229_0050_BHMYNGDRXY_NGS446_NGS445A_NGS444
echo $project_name |  grep -o 'NGS.*'
NGS446_NGS445A_NGS444
project_name=002_211217_NB551068_0434_AHG32FAFX3_NGS452A
echo $project_name |  grep -o 'NGS.*'
NGS452A
```
___
*[src/code.sh, line 19 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPyLM136lC7VVdL6uZ:-MrY7LHP4IU2-qlnzCER:bvf5iae) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L19)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

where is $bedfile_prefix made? this is a helper variable - should it be $subpanel_bed_prefix? 
</blockquote></details>

Unsure - see comment regarding docker command
___
*[src/code.sh, line 25 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-k8lElgom6Sjz06a:-MqoIkaoCBe6ke6J38MX:bx23w1x) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L25)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

duplicate comment
</blockquote></details>

Removed duplicate comment
___
*[src/code.sh, line 28 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-lu_1UsmXpEP1yiH:-MqoKAoW5Q2C5vpClANO:bg7h5ty) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L28)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Removed commented out code
___
*[src/code.sh, line 30 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-qQS34AdxhCPexv1:-MqoKUtf404sVYemGejB:bptxxkz) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L30)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not making
</blockquote></details>

Corrected comment
___
*[src/code.sh, line 35 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPymyhCXQA3cYPc17D:-MrP9UaC6AdxcW0E5SDg:b-xbdynk) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L35)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as above where is $bedfile_prefix made? this is a helper variable - should it be $subpanel_bed_prefix?
</blockquote></details>

$bedfile_prefix no longer used, see commendt relating to docker command.
___
*[src/code.sh, line 36 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ02mE0_eIUsD19cML:-MrPA2oE2zzowMiKHnx4:bbtp21u) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L36)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what is samplename showing? it's not for a specific sample?
</blockquote></details>

Moved in curent version to for loop where docker is run so that its use is clearer
___
*[src/code.sh, line 39 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ09VI91Vbth_RbY4w:-MrPCoVJ7wR9iPi8tk5G:bdmgamt) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L39)):*
> All Pan numbers to be assessed using this BED file
Ammended output print statement
___
*[src/code.sh, line 40 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ0GnP9cFHYr7IK3kL:-MrPD6xzCMLX1NZOwMbA:b-iyuao) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L40)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

where is this coming from?
</blockquote></details>

Removed from current version
___
*[src/code.sh, line 61 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzC_p63UIowX4y2QP:-MrP6kMxEuE_8z4niDg5:bpvbevv) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L61)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

? where is this coming from
</blockquote></details>

replaced with bam_list=(/home/dnanexus/to_test/*bam)
___
*[src/code.sh, line 65 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzFeq8TC6wC-ZnrQp:-MrPDEJ029k5aZviWhFv:b9xgsgc) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L65)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this still valid/needed?
</blockquote></details>

Probably, the exomeDepth.R code does an explicit check for at least 3 files - probably better to have the check here than getting some esoteric error message thrown by R in the docker container. 
___
*[src/code.sh, line 72 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzLSPAnqrdJzgqOiy:-MrP7Jki3WY46k-X2ft9:b-n6bn9z) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L72)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

not needed anymore?
</blockquote></details>

I've removed extraneous lines of code
___
*[src/code.sh, line 80 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzR8758saz8O7EdZ0:-MrP7UijEPhXPN9AJ_kJ:b-xy3dlx) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L80)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

assume this is packaged up in the app and in .gitignore? (gitignore not in the repo)
</blockquote></details>

I now explicitly download the docker from 001_ToolsReference project
___
*[src/code.sh, line 82 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPz_q7491hD_phgfJn:-MrP7dEb1crzOKUSmHlV:b-s09pfk) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L82)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this needed?
</blockquote></details>

I've removed it - from what Natasha said I don't think they were using a PoNs - if it needs to be reinstated it is in version control.
___
*[src/code.sh, line 85 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqPzgiXA17SSGH-1GW4:-MrY63e84uL0AixIicRA:bbp7iqq) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L85)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what would this return. split on /? assume that's removing the filepath /home/dnanexus/to_test?
</blockquote></details>

It wasn't working for me - got error message saying python not recognised asking for python3/python2 etc - replaced with samplename=$(basename "$bam" _R1_001.bam)  to get the filename without the _R1_001.bam suffix
___
*[src/code.sh, line 89 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-040-h_DX_DkGu0g:-MrY711UCEu2s4KjK8K5:bs6pwa9) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/src/code.sh#L89)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> v1.0.0
> ```
what is this? can you explain the cmd in comments please?
</blockquote></details>

I've added to the comments - a string basically concatenated to the output by exomeDepth.R to record the app version
___
*[src/code.sh, line 77 at r7](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MrY8sv35edV2h4TcqvL:-MrY8sv4-V8GOc8318vF:b-p9ejo6) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/ed52da152beaf6cd1fc1d20adef95fa0a12d4f19/src/code.sh#L77)):*
> ```Shell
> echo "bam:"$bam
> #for each bam run exomedepth
> docker run -v /home/dnanexus:/home/dnanexus seglh/exomedepth:5f792cb exomeDepth.R 'v1.0.0' /home/dnanexus/out/exomedepth_output/exomedepth_output/"$samplename"_output.pdf $subpanel_bed_path:$subpanel_bed_prefix $readcount_file_path $bam:$samplename $QC_file_path
> ```

Currently testing/troubleshooting the docker command to exomeDepth.R

**Review by aledj2 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1)* status: 2 of 5 files reviewed, 18 unresolved discussions (waiting on @aledj2, @Graeme-Smith, and @natashapinto)

___
*[dxapp.json, line 14 at r8](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MsBrYZwEW6guULyxPbD:-MsBrYZx5bTSVBbic6oR:bt4km14) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/5b953c91a8b937e4e13f7bf4181b5567746ab21f/dxapp.json#L14)):*
> ```JSON
>     },
>     {
>       "name": "reference_genome",
> ```

is this used? If it is please see changes to https://github.com/moka-guys/dnanexus_ED_readcount_analysis/blob/f06f085772821fb82c884467fb591f1959092a59/src/code.sh#L22

**Review by aledj2 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 2 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @Graeme-Smith)

___
*[README.md, line 8 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_ed_cnv_calling/1#-MqQ-I956yWY4f9kJR5w:-Msaq0d43pmU-uePJliG:b-bu9xvr) ([raw file](https://github.com/moka-guys/dnanexus_ed_cnv_calling/blob/6d0d271472d626b6a88e150227d321effba91233/README.md#L8)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

The script now downloads this from the 001_ToolsReference project
</blockquote></details>

can you link to the version/name?

**Pull request merged**
